Feat/add component event warning
VacuumORG/forum_vacuum_front pull request #15
Opened 2023-04-28 22:28 UTC by ArthurFilho

Foi criado o componente de Event Warning

- Criado componente do event warning
- Adicionado estilos ao componente event warning

2023-04-29 00:58 UTC, RickChaves29 commented
Não passou na formatação do linter

2023-04-29 19:04 UTC, RickChaves29 requested changes
Então notei a falta de uma boa semântica HTML no seu componente 
Pontos que poderia melhorar
1. Poderia trocar o uso das tag h1 e h2 no seu container onde ficas os dados de mês e dia, para o uso das Tags span ou time, e incluir o atributo datetime e receber esses dados como props
```jsx
    <div className="text-xl  flex flex-col items-center p-3 rounded-md theme-date">
        <span  className="mb-2 font-bold h-full theme-event-warning-title-and-date">
          {month}
        </span>
        <span className="text-3xl font-bold theme-author">{day}</span>
    </div>
``` 
ou 

```jsx
    <div className="text-xl  flex flex-col items-center p-3 rounded-md theme-date">
        <time datetime={datetime} className="mb-2 font-bold h-full theme-event-warning-title-and-date">
          {month}
        </time>
        <time datetime={datetime} className="text-3xl font-bold theme-author">{day}</time>
    </div>
``` 
2. Tentar por o nome das classes de tema ao final ou no começo para quem tá olhando visualizar o que é classe tailwind e o que é classe de tema

2023-04-29 21:38 UTC, RickChaves29 approved these changes
Muito bom !

2023-04-30 01:50 UTC, Ranieeery approved these changes

2023-04-30 02:32 UTC, offkevyn approved these changes

2023-04-30 02:38 UTC, merged