feat: create component menu
VacuumORG/forum_vacuum_front pull request #20
Opened 2023-05-01 05:32 UTC by offkevyn

2023-05-01 05:41 UTC, dayanecol approved these changes

2023-05-01 18:46 UTC, RickChaves29 requested changes
Então pontos a se atentar
- Melhorar a semântica do seu componente, usou de modo exagerado a tag div
- Quando você usa o componente IconButton, você está deixando um onClick e um console.log se necessidade
- No seu PR na pasta public a um arquivo com o nome vaccum_logo1.svg que não faz parte do componente 
- E os invés de usar a tag nav, recomento do uso da tag header por se trata do componente que ficara no tipo da pagina
- Quando for estiliza com cores o seu componente sete as cores no arquivo theme.css usando uma class ex: .theme-component-any

2023-05-02 22:54 UTC, RickChaves29 approved these changes

2023-05-03 01:49 UTC, ArthurFilho approved these changes

2023-05-03 04:29 UTC, merged