feat/Added Code Quality Check
VacuumORG/forum_vacuum_front pull request #48
Opened 2023-05-05 14:14 UTC by Diegiwg

O CodeQL é recomendado pelo GitHub como verificado de qualidade e segurança da base de código.

É grátis, e funciona plug-in-play. 

Não temos motivos para não utilizar.

2023-05-05 17:59 UTC, RickChaves29 reviewed
Vou avaliar a doc antes, já retorno com a resposta

2023-05-06 06:12 UTC, RickChaves29 requested changes
Vai ser excelente a adição desta funcionalidade ao projeto, só peço que faça uma modificação 
Remova a 15 e 16 
```yaml
push:
    branches: ['main']
```
Pois não vai ser necessário a checagem em push na main, apenas em pull requests para a main

2023-05-06 10:49 UTC, Diegiwg commented
> Vai ser excelente a adição desta funcionalidade ao projeto, só peço que faça uma modificação Remova a 15 e 16
> 
> ```yaml
> push:
>     branches: ['main']
> ```
> 
> Pois não vai ser necessário a checagem em push na main, apenas em pull requests para a main

Corrigi querido.

2023-05-06 17:41 UTC, RickChaves29 approved these changes

2023-05-06 17:41 UTC, Jackson-SM approved these changes

2023-05-07 01:23 UTC, BarbosaThaissa approved these changes

2023-05-07 01:24 UTC, merged