fix: turn the request private
VacuumORG/forum_vacuum_front pull request #56
Opened 2023-05-06 23:15 UTC by Luciano-Ferreira

req to _req

2023-05-06 23:18 UTC, Diegiwg requested changes
Leia o novo documento [Padrões da API](https://gist.github.com/Diegiwg/418b9da74cab03bcc07c92011e22beb5), e aproveite para ajustar essa rota a ele. Não fez sentido apenas modificar o `req`, já que toda a estrutura está invalida agora.

2023-05-08 02:19 UTC, RickChaves29 approved these changes

2023-05-08 02:20 UTC, Diegiwg approved these changes

2023-05-08 20:06 UTC, Jackson-SM approved these changes

2023-05-08 20:06 UTC, merged