Feat/create route topics/id]/views
VacuumORG/forum_vacuum_front pull request #94
Opened 2023-05-18 17:09 UTC by medeirosdev

Basicamente foi criado uma nova rota, a partir de topics/[id], a topics/[id]/views, quando é acessada através do método PATCH ela incrementa +1 no valor 'views' ta tabela topics

2023-05-18 17:21 UTC, Jackson-SM approved these changes

2023-05-18 17:22 UTC, Jackson-SM commented
Opa, medeiro, beleza?
Se possível, tire a String "example" que colocou dentro do arquivo .env.example

2023-05-18 17:25 UTC, Jackson-SM requested changes
Edite o arquivo .env.example e o "example" que adicionou. Você retirou o SUPABASE_URL e SUPABASE_KEY que são coisas importantes pra configuração do database.

2023-05-18 17:45 UTC, Jackson-SM approved these changes

2023-05-18 17:45 UTC, Jackson-SM commented on .env.example
> -SUPABASE_KEY=
Adicione essas linhas novamente

2023-05-18 18:52 UTC, Diegiwg requested changes
Remova a edição do arquivo .env.example

2023-05-18 18:54 UTC, Diegiwg commented
Como essa rota vai lidar com a questão de uma pessoa já ter visualizado a post, e for visualizar novamente? Vai contabilizar duas visualizações?

2023-05-19 00:01 UTC, Jackson-SM commented
> Como essa rota vai lidar com a questão de uma pessoa já ter visualizado a post, e for visualizar novamente? Vai contabilizar duas visualizações?

O foco é apenas a funcionalidade por agora, depois iremos focar nessa parte mais técnicas e detalhadas.

2023-05-22 13:34 UTC, Diegiwg approved these changes

2023-05-22 19:04 UTC, Luciano-Ferreira approved these changes

2023-05-22 19:04 UTC, Luciano-Ferreira commented on src/pages/api/v1/topics/[id]/views/index.ts
> +  } else if (topicsN && topicsN.length > 0) {
estamos evitando usar else if para que o código fique mais facil de ler para todos.
e retornar o erro se houver.

```javascript
if (topicsError) {
return res.status(CodeServerError.InternalServerError).json(topicsError)
}

if (topicsN && topicsN.length > 0) {
// ...
}
```

2023-05-22 19:57 UTC, merged